   
    SELECT * FROM SALES;

    ---1st question---
    
    SELECT DISTINCT(CUSTOMERNAME) FROM SALES
     WHERE COUNTRY='USA';

     ---2nd question---

     SELECT COUNT( DISTINCT CUSTOMERNAME) AS TOTAL_CUSTOMERS FROM SALES
     WHERE SALES>5000;

     ---3rd question---

     SELECT COUNT( DISTINCT ORDERNUMBER) AS TOTAL_PRODUCTS FROM SALES
      WHERE YEAR_ID=2003;

    ---4rth question---

     SELECT SUM(SALES) AS TOTAL_SALE_PRICE FROM SALES WHERE YEAR_ID=2005;

    ---5th question---

     SELECT YEAR_ID,SUM(SALES) AS TOTAL_SALE_PRICE FROM SALES
     GROUP BY YEAR_ID
     ORDER BY YEAR_ID;